---
name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  continous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install uv
      - name: Check formatting with ruff
        run: |
          uvx ruff format --diff
      - name: Lint with ruff
        run: |
          uvx ruff check
      - name: Run unit tests
        run: |
          uv run pytest
      - name: Build distribution artifacts
        run: |
          uv build
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distribution
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs:
      - continous-integration

    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/evdevremapkeys
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
      name: Publish to TestPyPI
      needs:
        - continous-integration

      runs-on: ubuntu-latest

      environment:
        name: testpypi
        url: https://test.pypi.org/p/evdevremapkeys

      permissions:
        id-token: write  # IMPORTANT: mandatory for trusted publishing

      steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distribution
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/